### ISSUE TITLE
Missing build.gradle and settings.gradle for root project

### ISSUE THREAD

**Issue by krt16s** [Kadabash/SyncOnWifi#1]
The source only includes the subproject's `./app/build.gradle` but is missing the build files for the root project in `./build.gradle` and `./settings.gradle`.

**Comment by Kadabash** [comment]
Thanks for pointing that out.
I just added those in this commit: f20e84ca61b1589734c5648f561912db4b3122e3 . 
Were those the only two files that were missing?

**Comment by krt16s** [comment]
Yep, thanks for the quick response.
