### ISSUE TITLE
Crash while click on "select wifi networks"

### ISSUE THREAD

**Issue by YoungNFoolish** [Kadabash/SyncOnWifi#4]
Hi,
The app crashes while i click on select wifi networks.
My phone is Huawei p9 lite (running EMUI 5.0, android 7.0).

**Comment by Kadabash** [comment]
Hey, could you provide any logs? Just google "logcat android". Alternatively, please post a screenshot of your settings in the app. Then I could try to reproduce your error.

**Comment by YoungNFoolish** [comment]
Today when i tried to test it again and read logcat, didn't crash. I don't know what is going on!
Sorry to bothering you. I suppose the issue can be closed for now.

**Comment by YoungNFoolish** [comment]
I find out something.
Actually the app crashes on "select wifi networks" IF phone is not connected to any wifi.
It supposed to show a list of known wifi SSIDs instead of crash! So, what's next?!

**Comment by Kadabash** [comment]
It seems I can reproduce the issue on my device. I'll look into it in the next few days.

**Comment by Kadabash** [comment]
Fixed in commit dc7cfcb0f1d7b6435c59991279bc05f9ab30e184.
Please check if it is indeed fixed for you, if possible.

**Comment by YoungNFoolish** [comment]
Yeah, it's fixed. Thanks
