### ISSUE TITLE
Eventually Stops Working

### ISSUE THREAD

**Issue by JSB2000** [Kadabash/SyncOnWifi#7]
I have this installed on a non-rooted phone running Android 5.1.  It works properly for a while but eventually stops (accounts keep trying to sync despite not being connected to the only allowed WIFI networks).  I leave the house, go beyond the range of my WIFI, and the accounts still try to sync.

The only way to get it working again is to go through the entire setup procedure again (sometimes several times): Disable/enable the service, de/reselect the accounts, de/reselect the WIFI networks.

My intuitive guess is that the service is somehow getting knocked out of memory and is not re-reading the settings (or able to grab control of the sync accounts?).  Going through the setup procedure "wedges it back in place?"

Perhaps a persistent notification would help keep it where it should be on non-rooted devices?

**Comment by Kadabash** [comment]
Thanks for your bug report! <br> This is strange behaviour, since the app does not have a background service per se. Instead, it uses Androids system broadcasts to trigger all actions, i.e. nothing runs in the background at all. Therefore, I do not think it is a memory related issue. I'll try to reproduce what you describe.

**Comment by Kadabash** [comment]
I have been able to reproduce part of your problem and have written a fix. Kindly install my test build (either unzip the apk attached below, or build the "v1.0.x" branch) and see if this fixed your issues. <br><br>[SyncOnWifi_v1_0_2test.apk.zip](https://github.com/Kadabash/SyncOnWifi/files/1133209/SyncOnWifi_v1_0_2test.apk.zip)

**Comment by JSB2000** [comment]
Will test over the next few days and let you know the results.  Thanks for your efforts!

**Comment by JSB2000** [comment]
Well, so far, so good.  Sync is now happening only when it's supposed to.  Have been in and out of the office many times over the past two days.  Each time I leave range of the allowed networks, no more stray syncs.  As soon as I pick up an allowed network: Boom, sync starts right back up again.

Bravo! Looks like a winner.  Let me know if you require me to perform any additional tests.  If not, I'll close the issue and await the fix's integration into a subsequent release.

**Comment by Kadabash** [comment]
Thank you very much for your support in fixing this. In my testing for the last few days, I had some battery drain issues, although I am not sure whether those came from other software changes on my phone. Did you experience any issues concerning battery life or high CPU load, etc? If not, I will make a new release immediately.

**Comment by JSB2000** [comment]
You're very welcome and, no, no excess battery drain or CPU spikes that I could see.  And, trust me, that's something I'd notice: Was using mapping and GPS extensively over the last few days (which kill my battery/load the CPU as it is).  If your app had added to that, I'd be...lost? <grin>

Closing the issue and awaiting the new release.  Thanks again!
